# Shoppy.gg Order Spammer Bot Config #

# Discord bot token
discord_token: ""
# Discord bot prefix
bot_prefix: "."
# Discord logs channel id
logs_channel: 0123456789
# Loading green emoji id
loading_green_emoji_id: ""
# Loading red emoji id
loading_red_emoji_id: ""
# Green tick emoji id
green_tick_emoji_id: ""
# User timeout (seconds)
user_timeout:
